// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5sGC5ayVjRVLPsq19jX3yFk1BCKtbC04',
    appId: '1:332461388821:web:76a8caf81e62dca7b88a1c',
    messagingSenderId: '332461388821',
    projectId: 'pampan-20d42',
    authDomain: 'pampan-20d42.firebaseapp.com',
    storageBucket: 'pampan-20d42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9jPoYANB_YGQbP-IHRaR4u5F8_-S32_A',
    appId: '1:332461388821:android:25bc7777643c8b7fb88a1c',
    messagingSenderId: '332461388821',
    projectId: 'pampan-20d42',
    storageBucket: 'pampan-20d42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAexfsDMQyltZIG7cY0tRMWnStHQte7_mA',
    appId: '1:332461388821:ios:6eeadb164940f1b8b88a1c',
    messagingSenderId: '332461388821',
    projectId: 'pampan-20d42',
    storageBucket: 'pampan-20d42.appspot.com',
    iosBundleId: 'com.example.pamPan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAexfsDMQyltZIG7cY0tRMWnStHQte7_mA',
    appId: '1:332461388821:ios:6eeadb164940f1b8b88a1c',
    messagingSenderId: '332461388821',
    projectId: 'pampan-20d42',
    storageBucket: 'pampan-20d42.appspot.com',
    iosBundleId: 'com.example.pamPan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5sGC5ayVjRVLPsq19jX3yFk1BCKtbC04',
    appId: '1:332461388821:web:0469c8a4e1b0c331b88a1c',
    messagingSenderId: '332461388821',
    projectId: 'pampan-20d42',
    authDomain: 'pampan-20d42.firebaseapp.com',
    storageBucket: 'pampan-20d42.appspot.com',
  );
}
